# Generated by Django 4.2.4 on 2023-08-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=248)),
                ('id_of_model', models.IntegerField()),
                ('image', models.BinaryField()),
                ('caption', models.TextField(max_length=400)),
                ('original_price', models.IntegerField()),
                ('offed_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ViewCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('caller', models.CharField(default='counter', max_length=7)),
            ],
        ),
    ]
