# Generated by Django 4.2.4 on 2023-08-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KianV0_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopitem',
            name='id_of_model',
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
