# Generated by Django 4.2.4 on 2023-08-30 20:07

import KianV0_App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KianV0_App', '0002_remove_shopitem_id_of_model_alter_shopitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='image',
            field=models.ImageField(upload_to=KianV0_App.models.generate_image_path),
        ),
    ]
