# Generated by Django 4.2.4 on 2023-08-31 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KianV0_App', '0003_alter_shopitem_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopitem',
            old_name='offed_price',
            new_name='mareket_price',
        ),
        migrations.RenameField(
            model_name='shopitem',
            old_name='original_price',
            new_name='offered_price',
        ),
        migrations.AddField(
            model_name='shopitem',
            name='is_is_stock',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
