# Generated by Django 4.2.4 on 2023-08-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KianV0_App', '0005_alter_shopitem_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='mareket_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='offered_price',
            field=models.FloatField(),
        ),
    ]
