# Generated by Django 4.2.4 on 2023-09-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KianV0_App', '0006_alter_shopitem_mareket_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='order_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='is_is_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='mareket_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='offered_price',
            field=models.FloatField(default=0.0),
        ),
    ]
